/*****************************************************************/
/*                                                               */
/* FILE        : BSP.c                                           */
/* DATE        : 2015-04-20                                      */
/* AUTHOR      : Cao ChenGuang                                   */
/* DESCRIPTION : BSP basic support functions.                    */
/* NOTE        : All Rights reserved by DETC, Technology Center  */
/*                                                               */
/*****************************************************************/
#include "BSP.h"

/* header files from rappid */
#include "jdp.h"
#include "sys_init.h"
#include "rappid_utils.h"

/* header files from MCUAbstraction */
#include "ee_types.h"
#include "SIUL.h"
#include "PIT.h"
#include "MCU_SwitchMode.h"
#include "Watchdog.h"

/* header files form ECUAbstraction */
#include "IODefine.h"
#include "ECU_DataFlash.h"
#include "Sound.h"
#include "RTC.h"
#include "Indicator.h"
#include "Display.h"

/* header files from platform */
#include "ModeManager.h"
#include "Scheduler.h"
#include "CAL.h"
#include "Transport.h"

void main(void)
{
	DisableExternalInterrupts();
    sys_init_fnc();               /* MCU registers initialization, codes are generated by rappid */

    /* initialize peripherals in low-power mode */
    MCU_LowPowerModeEnter();
    (void)ECU_Init_Eeprom();
    CAL_Init();
    ECU_MatrixLcd_Init();        /* Monochrome must be initialized without interruption */
    ECU_Sound_Init();
    ECU_Indicator_Init();
    ECU_Rtc_Init();
    BSP_Set_CanTrcvMode(0u, BSP_CANTRCV_NORMAL);
    BSP_Set_CanTrcvMode(1u, BSP_CANTRCV_STANDBY);

    APPL_Init();
    EnableExternalInterrupts();
	APPL_Start();
}

/*
 * Name        : PIT_ISR0
 * Description : PIT timer 0 ISR
 * Arguments   : none
 * Return      : none
 */
void PIT_ISR0(void)
{
    CLEAR_PIT_INT_FLAG(0);       /* clear PIT 0 interrupt flag */
    APPL_Run();
    BSP_ActiveBuzzerRun();
    Trans_Run(); /* TODO: it is not proper to place "Trans_Run();" here */
}


void ECU_WdgMgr_Init(void)
{
    MCU_EnableWatchdog();
}

void ECU_WdgMgr_Runnable(void)
{
    MCU_ClearWatchdog();
}
/*
 * Name        : BSP_Set_CanTrcvMode
 * Description : set can transmit or receive mode
 * Arguments   : CanChannel : 0 - CAN channel0
 *                            1 - CAN channel1
 * Return      : none
 */
void BSP_Set_CanTrcvMode(uint8 CanChannel, BSP_CanTrcvMdType NewMode)
{
    if(CanChannel == 0)
    {
    	if(NewMode == BSP_CANTRCV_NORMAL)
    	{
    		SIUL_Output(CAN0_STB, 0);
    	}
    	else if(NewMode == BSP_CANTRCV_STANDBY)
    	{
    		SIUL_Output(CAN0_STB, 1);
    	}
    	else
    	{
    		;
    	}
    }
    else if(CanChannel == 1)
    {
	    if(NewMode == BSP_CANTRCV_NORMAL)
	    {
	    	SIUL_Output(CAN1_STB, 0);
	    }
	    else if(NewMode == BSP_CANTRCV_STANDBY)
	    {
	    	SIUL_Output(CAN1_STB, 1);
	    }
	    else
	    {
	    	;
	    }
    }
    else
    {
    	;
    }	
}

/*
 * Name        : BSP_EnterCriticalSection
 * Description : 
 * Arguments   : None
 * Return      : None
 */
void BSP_EnterCriticalSection(void)
{
    asm(" wrteei 0");
}

/*
 * Name        : BSP_LeaveCriticalSection
 * Description : 
 * Arguments   : None
 * Return      : None
 */
void BSP_LeaveCriticalSection(void)
{
    asm(" wrteei 1");
}

BSP_StdReturnType BSP_Service_GetPartNumber(uint32* PartNumber)
{
    *PartNumber = 0u;
    /* TODO: to be implemented */
}

BSP_StdReturnType BSP_Service_GetRevision(uint8* Revision)
{
    *Revision = 0u;
    /* TODO: to be implemented */
}

