#ifndef __TPMS_H
#define __TPMS_H

#define VALID_LOW_LIMIT (0U)
#define VALID_HIGH_LIMIT (2000U)
#define NO_WARNING_PRESSURE (0x02U)

#define NUMBER_OF_TIRES (10U)
#define TPMS_TIRE_PRESSURE_GAIN (8U)

#define TIRE_LOCATION_MASK (0xF0U)
#define TPMS_FRONT_LEFT_TIRE (0x10U)
#define TPMS_FRONT_RIGHT_TIRE (0x11U)
#define TPMS_MIDDLE_AXLE_LEFT_OUTER_TIRE (0x20U)
#define TPMS_MIDDLE_AXLE_LEFT_INNER_TIRE (0x21U)
#define TPMS_MIDDLE_AXLE_RIGHT_INNER_TIRE (0x22U)
#define TPMS_MIDDLE_AXLE_RIGHT_OUTER_TIRE (0x23U)
#define TPMS_REAR_AXLE_LEFT_OUTER_TIRE (0x30U)
#define TPMS_REAR_AXLE_LEFT_INNER_TIRE (0x31U)
#define TPMS_REAR_AXLE_RIGHT_INNER_TIRE (0x32U)
#define TPMS_REAR_AXLE_RIGHT_OUTER_TIRE (0x33U)

void TPMS_Run(void);
void TPMS_Init(void);

#endif // __TPMS_H
